.TH "QDIRSTAT" "1" "July 2017"
.SH NAME
qdirstat \- Qt\-based directory statistics
.SH DESCRIPTION
QDirStat is a graphical application to show where your disk space has gone and
to help you to clean it up.
.PP
Usage:
.IP
qdirstat [\-\-slow\-update|\-s] [<directory\-name>]
qdirstat \fB\-\-cache\fR|\-c <cache\-file\-name>
qdirstat \fB\-\-help\fR|\-h
.PP
.SH "AUTHOR"
This manual page was written by Patrick Matth\[:a]i <pmatthaei@debian.org>
for qdirstat.
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU General Public License, Version 2 any
later version published by the Free Software Foundation.
