#!/usr/bin/env python3

#
# Converts output from "rclone lsf -R --format 'stmp' --csv" into qdirstat cache format.
# This allows to create remote directory listings with rclone and inspect their disk usage with qdirstat.
#
# See https://github.com/shundhammer/qdirstat/blob/master/doc/cache-file-format.txt for output format.
#

import csv
from datetime import datetime
import os
import sys
import urllib.parse

if __name__ == "__main__":
    input_file = sys.argv[1]
    with open(input_file) as csv_fp:
        print(f'''[qdirstat 1.0 cache file]
# Generated by {os.path.basename(sys.argv[0])}
# Do not edit!
#
# Type  path            size    mtime

D\t/\t0\t0
''')

        csv_reader = csv.DictReader(csv_fp, ['size', 'mtime', 'mimetype', 'path'])
        for row in csv_reader:
            try:
                assert int(row['size']) >= -1, 'size must be an integer >= -1'
                formatted_size = '0' if row['size'] == '-1' else row['size']
                assert row['mimetype'].find('/') != -1, 'mime type must contain a slash'
                item_type = 'D' if row['mimetype'].startswith('inode/directory') else 'F'
                assert row['path'], 'path must not be empty'
                formatted_path = '/' + urllib.parse.quote(row["path"])
                mtime_unix_seconds = int(datetime.strptime(row['mtime'], '%Y-%m-%d %H:%M:%S').timestamp())
            except Exception as ex:
                sys.stderr.write(f'\nError reading {input_file}:{csv_reader.line_num}: {ex}.\nDid you run "rclone lsf" with "--format=stmp" and --csv parameters?\n')
                sys.exit(1)
            print(f'{item_type}\t{formatted_path}\t{formatted_size}\t{mtime_unix_seconds}')
